version: '3.3'
services:
  mysql:
    image: mysql/mysql-server:8.0           # The Docker image to use for the MySQL service
    environment:    
      MYSQL_DATABASE: 'db' 
      MYSQL_USER: 'user' 
      MYSQL_PASSWORD: 'password'  
    ports:            
      -  '3306:3306'

  flaskapp:
    image: flask-mysql:latest           # The Docker image to use for the Flask application service
    depends_on:       
      -  mysql
    environment:
      DATABASE_HOST: 'mysql'
      DATABASE_USER: 'user' 
      DATABASE_PASSWORD: 'password'
      DATABASE_NAME: 'db' 
    ports:
      -  '8000:3000'

## docker compose up
## docker compose down