version: '3.3'
services:
  mysql:
    image: mysql/mysql-server:8.0
    environment:
      MYSQL_DATABASE: 'db'        
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
    ports: 
      - '3306:3306'
    volumes: 
      - new-db:/var/lib/mysql #数据存在主机里，docker down之后数据还在

  flaskapp:
    image: grade-submission:0.0.1 # your image here
    depends_on:
      - mysql
    environment:
      DATABASE_HOST: 'mysql'
      DATABASE_USER: 'user'
      DATABASE_PASSWORD: 'password'
      DATABASE_NAME: 'db'
    ports: 
      - '8080:8080'
volumes:
  new-db: 

## docker system prune -a --volumes 删除卷volumes